Apply feedback from James
geojupyter/geojupyter.github.io pull request #4
Opened 2024-11-21 19:25 UTC by mfisher87

Thanks for this excellent input @colliand!

2024-11-22 20:33 UTC, fperez requested changes

2024-11-23 00:26 UTC, mfisher87 commented on LICENSE
> +for Data Science and Environment, UC Berkeley
Thanks for the guidance on this, Fernando! :rocket:

2024-11-23 00:30 UTC, mfisher87 commented on about.md
> +* [QuantStack](https://quantstack.net/)
Thanks for confirming this is the right track :100:

2024-11-23 00:32 UTC, mfisher87 commented on LICENSE
> +for Data Science and Environment, UC Berkeley
>Use language like Jupyter here ("GeoJupyter Contributors")

39c3f1f :rocket:

2024-11-23 00:32 UTC, mfisher87 commented on _quarto.yml
> +    left: "© 2024 The GeoJupyter community and the Eric & Wendy Schmidt Center for Data Science and Environment, UC Berkeley"
https://github.com/geojupyter/geojupyter.github.io/commit/39c3f1f5986d84bb4e7db9af5845a38624c673a0

2024-11-23 00:34 UTC, mfisher87 commented
I'm going to go ahead and get this change live, since it's important! Thanks all :)

2024-11-23 00:37 UTC, merged